version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@2.0.2

executors:
  node:
    docker:
      - image: cimg/node:22.18

jobs:
  # Smart autocancel - different strategies based on branch
  smart-autocancel:
    executor: node
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: |
            corepack enable
            corepack prepare pnpm@latest --activate
      - run:
          name: Build and run smart autocancel
          command: |
            echo "========================================="
            echo "Smart autocancel for branch: $CIRCLE_BRANCH"
            echo "========================================="
            pnpm install --frozen-lockfile
            pnpm run build

            if [[ "$CIRCLE_BRANCH" == "main" || "$CIRCLE_BRANCH" == "master" ]]; then
              echo "On default branch - cancelling only setup workflows"
              node dist/cli.js \
                --workflow-name "setup" \
                --verbose \
                --max-pages 3
            else
              echo "On feature branch - cancelling ALL old workflows"
              node dist/cli.js \
                --name-pattern ".*" \
                --verbose \
                --max-pages 5
            fi

            echo "Smart autocancel completed"

workflows:
  setup:
    jobs:
      # Smart autocancel based on branch type
      - smart-autocancel:
          context:
            - circleci-api

      # Then proceed with path filtering
      - path-filtering/filter:
          name: check-updated-modules
          requires:
            - smart-autocancel
          mapping: |
            packages/frontend/.* run-frontend true
            packages/backend/.*  run-backend true
            packages/shared/.*   run-shared true
            docs/.*              run-docs true
            .circleci/.*         run-all true
          base-revision: main
          config-path: .circleci/continue-monorepo.yml
